export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_REQUEST_SUCCESS = 'GET_PRODUCT_REQUEST_SUCCESS';
export const GET_PRODUCT_REQUEST_FAILED = 'GET_PRODUCT_REQUEST_FAILED';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_REQUEST_SUCCESS = 'DELETE_PRODUCT_REQUEST_SUCCESS';
export const DELETE_PRODUCT_REQUEST_FAILED = 'DELETE_PRODUCT_REQUEST_FAILED';

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_REQUEST_SUCCESS = 'PRODUCT_UPDATE_REQUEST_SUCCESS';
export const PRODUCT_UPDATE_REQUEST_FAILED = 'PRODUCT_UPDATE_REQUEST_FAILED';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_REQUEST_SUCCESS = 'ADD_PRODUCT_REQUEST_SUCCESS';
export const ADD_PRODUCT_REQUEST_FAILED = 'ADD_PRODUCT_REQUEST_FAILED';
